### ISSUE TITLE
Why use different domain names to identify services in multi regions?

### ISSUE THREAD

**Issue by jetbldr** [bnb-chain/bsc-mev-info#28]
If this strategy is to facilitate faster access for validators and searchers in different regions, then why not use a geo-based resolution strategy? e.g. aws [Geolocation routing ](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-geo.html)

This way, only one domain name needs to be maintained.

**Comment by realuncle** [comment]
We dont mind what's the stratery each builder is applying.
